### ISSUE TITLE
DeploymentExcetion: Connection failed with Java 17

### ISSUE THREAD

**Issue by Schoaf** [daniel-sc/rocketchat-modern-client#30]
Hi there,
you client works with Java 16, but with OpenJDK 17 there is an Exception.
Can you test that? Maybe it's just a dependency that has to be updated (glassfish).

Tested with version 1.3.2

`Java Version: 17.0.3.1
Java Version: 17.0.3.1+2-LTS-6
Java Runtime Name: Java(TM) SE Runtime Environment
Java Vm name: Java HotSpot(TM) 64-Bit Server VM`

`javax.websocket.DeploymentException: Connection failed.
	at org.glassfish.tyrus.container.jdk.client.JdkClientContainer.openClientSocket(JdkClientContainer.java:192)
	at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:493)
	at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:355)
	at com.github.daniel_sc.rocketchat.modern_client.RocketChatClient.connect(RocketChatClient.java:110)
	at com.github.daniel_sc.rocketchat.modern_client.RocketChatClient.loginBase(RocketChatClient.java:149)
	at com.github.daniel_sc.rocketchat.modern_client.RocketChatClient.login(RocketChatClient.java:137)
	at com.github.daniel_sc.rocketchat.modern_client.RocketChatClient.<init>(RocketChatClient.java:61)
	at com.github.daniel_sc.rocketchat.modern_client.RocketChatClient.<init>(RocketChatClient.java:55)
	at at.cpbs.ebanking.serenity.helper.RocketChatHelper.listenToDeviceNotifictaionsChannel(RocketChatHelper.java:32)
	at at.cpbs.ebanking.serenity.steps.LoginSteps.registerPrimaryDevice(LoginSteps.java:53)
	at at.cpbs.ebanking.serenity.steps.LoginSteps.loginWithDeviceRegistration(LoginSteps.java:38)
	at at.cpbs.ebanking.serenity.LoginTest.firstLoginTest(LoginTest.java:25)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)`

**Comment by daniel-sc** [comment]
@Schoaf integration tests work fine with java 17 - see https://github.com/daniel-sc/rocketchat-modern-client/blob/master/.github/workflows/build-and-test.yaml#L16 (it uses "AdoptOpenJdk" flavour).

Are you sure the only difference is the JDK? Could there be other connectivity issues?

**Comment by Schoaf** [comment]
I really tried just now. I just switched JDK and got the same error. Worked fine before.
The IT is not really connecting to any server. Have you tried to connect to a server? 
Or is there a difference in the WS protocoll or something. Maybe I should have a look in the RocketChat logs as well...

Anything else I could try out?

**Comment by daniel-sc** [comment]
The IT is actually connecting to wss://open.rocket.chat:443/websocket (see https://github.com/daniel-sc/rocketchat-modern-client/blob/master/src/test/java/com/github/daniel_sc/rocketchat/modern_client/RocketChatClientIT.java#L39)

I'll try to reproduce this next week. If you find a solution by then, please feel free to start a PR :)

**Comment by Schoaf** [comment]
I just tried again. The only thing I change is the Execution Environment.

Does not work:
`Java Version: 17.0.3.1
Java Version: 17.0.3.1+2-LTS-6
Java Runtime Name: Java(TM) SE Runtime Environment
Java Vm name: Java HotSpot(TM) 64-Bit Server VM`

Works:
`Java Version: 16.0.2
Java Version: 16.0.2+7
Java Runtime Name: OpenJDK Runtime Environment
Java Vm name: OpenJDK 64-Bit Server VM`

Downloaded the one from the Eclipse Foundation - does also not work:
`Java Version: 17.0.3
Java Version: 17.0.3+7
Java Runtime Name: OpenJDK Runtime Environment
Java Vm name: OpenJDK 64-Bit Server VM`

I'll keep you posted...

**Comment by Schoaf** [comment]
Okay, I am so sorry.
It was a certificate issue that was capsuled inside the DeploymentException. 
Everything works with Java 17 now.
Thanks for the fast response though!
